version: '3.9'

services:
    client.api:
        container_name: client.api
        build:
            context: .
            dockerfile: ClientAPI/Dockerfile
        ports:
            - "8080:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - ConnectionStrings:ClientDb=Server=db;Database=client.db;User=sa;Password=root@1234;Encrypt=False;
        depends_on:
            - db
    db:
        container_name: db
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - MSSQL_SA_PASSWORD=root@1234
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433"
        volumes:
            - sqlserverdata:/var/opt/mssql

volumes:
    sqlserverdata:
